### ISSUE TITLE
Simplify the UI

### ISSUE THREAD

**Issue by Alix-Eisenhardt** [Boxadactle/coordinates-display#10]
I really like the coord mod from LunarClient and I would like to be able to find a mod that could do the exact same things, being

- Display the facing direction where your Chunk Coords are, shortened and with +/- indicating how coordinates are changing, it's really intuitive and small
- Put the chunk coords right below the block coords (for the people who want them)
- Only display the biome name without having the "Biome" label present (because i don't think it's relevant and it takes space) and if possible, use the preset color

It would make a great mod for everyone to use, it would be small enough to not distract the player to taking too much screen space while always having all the needed information right there

Here's an image of the lunar version for reference
![image](https://user-images.githubusercontent.com/19970562/218360177-40c8adb8-b619-45d2-83ae-a7fde7d8747f.png)

**Comment by Boxadactle** [comment]
I think I'll add this as a "minimum mode", or something like that. I don't quite understand the +/- aspect though (I haven't played Lunar client in a while), and how would that symbolize which direction you're facing?

**Comment by Alix-Eisenhardt** [comment]
+/- are there to know how coordinates will change if you go in the direction you're facing. 
The direction you're facing is between them (SW = South West)

**Comment by Boxadactle** [comment]
![2023-03-26_17 21 50](https://user-images.githubusercontent.com/109389081/227814329-f8e71b40-57d2-4b50-8ae9-b477fab5096f.png)
