### ISSUE TITLE
Show minecraft version like Alpha days

### ISSUE THREAD

**Issue by graemeg** [Boxadactle/coordinates-display#11]
**Is your feature request related to a problem? Please describe.**
No way to know the minecraft version without going into the Debug screen

**Describe the feature you'd like**
I would like to record my gameplay, but I would also like to record the version of Minecraft I'm using. Back in the Alpha days, Minecraft used to show the text `Minecraft vX.Y.Z` in the top left corner. Your mod already does an excellent job at displaying information (coords, biome etc). Having an extra option of the minecraft version above the coords would be absolutely perfect.

**Describe alternatives you've considered**
I don't know of other Fabric mods that do this. And I don't want to use the F3 Debug screen.

**Additional context**
none

**Comment by Boxadactle** [comment]
Would this be displayed as a part of the HUD, or separately?

**Comment by graemeg** [comment]
As part of the HUD should work fine, as long as one can select witch elements to make visible (I don't want all the various elements visible).

To give some context. I want to use your plug-in in my YouTube videos (credit will be given). I switch between various Minecraft versions, and don't want to keep remembering to note down the version of Minecraft, and then afterwards add it via the video editing software. It would be so much more convenient (and accurate) if the plug-in could display that for me as I record my gameplay. Like the old Alpha & Beta versions used to do.

**Comment by Boxadactle** [comment]
![Uploading Screenshot_19.png…]()

**Comment by Boxadactle** [comment]
![Screenshot_20](https://user-images.githubusercontent.com/109389081/227804089-afbc9959-4910-40d8-917c-394e28d424c7.png)

**Comment by graemeg** [comment]
Awesome, thank you very much.
