### ISSUE TITLE
needs updating for 1.19.4

### ISSUE THREAD

**Issue by Gareee** [Boxadactle/coordinates-display#14]
Pretty clear by title ;)

**Comment by boldandbrad** [comment]
Seconding this. Game crashes on load or on attempting to modify configs for this mod in 1.19.4

**Comment by ntoonio** [comment]
Updated fabric-version:

https://github.com/ntoonio/coordinates-display/releases/tag/1.19.4

**Comment by Boxadactle** [comment]
Sorry I've been adding new features, it should be finished soon.

**Comment by Boxadactle** [comment]
https://www.curseforge.com/minecraft/mc-mods/coordinates-display/files/all?filter-status=1&filter-game-version=2020709689%3A9776
