### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by f1xc0d3** [Boxadactle/coordinates-display#19]
https://scans.gradle.com/s/zueyryqkfjk7o

what am I doing wrong?

**Comment by Boxadactle** [comment]
Might be caused by modmenu recently moving their maven url, if you were building the fabric version.

**Comment by Boxadactle** [comment]
I've configured the dependencies incorrectly, should be fixed in a bit.

**Comment by Boxadactle** [comment]
Gradle has been configured completely incorrectly in both Fabric and Forge, finally fixed everything and will be releasing a fixed version soon.
