### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by ImOnTopL** [Boxadactle/coordinates-display#2]
Sometimes it disappears like when i click a button or something

**Comment by Boxadactle** [comment]
Do you know what button you pressed? Maybe you pressed the keybind that makes it disappear.

**Comment by Boxadactle** [comment]
The visible keybind toggles on/off the hud and it is O, maybe you pressed it. You can unbind it in the controls settings in the Minecraft options menu

**Comment by TheTrashCrafter** [comment]
No, its not because of the keybind, even if you unbind the keybind that bug happens.

**Comment by Boxadactle** [comment]
Do you know what button you pressed?

**Comment by TheTrashCrafter** [comment]
I pressed Escape and opened Mod Menu, after that the coordinates display doesn’t show up anymore. I think that only happens when you go into a GUI, where you cant see the game in the Background.

**Comment by ImOnTopL** [comment]
Yea for me tho if i unbind/bind it happens like if i press some key it
disappears

**Comment by Boxadactle** [comment]
@TheTrashCrafter, the HUD disappears when you enter the configuration GUI. This is to prevent it from rendering twice, since it is already rendered in the configuration GUI. When you exit the GUI, does it stay invisible?

**Comment by Boxadactle** [comment]
@ImOnTopL which version of this mod are you using? In the 1.19.2 version I can't find anything that would make the HUD disappear.

**Comment by TheTrashCrafter** [comment]
If i go into Mod Menu and then back to the game it no longer displays, if i go then in the configuration GUI and again back to the game it shows again.

**Comment by TheTrashCrafter** [comment]
Maybe it stops rendering when you go into Mod Menu, but only renders again if you exit the configuration GUI.

**Comment by Boxadactle** [comment]
I'm making a forge version and I need to update the fabric version. I'll fix this bug in those versions of the mod

**Comment by TheTrashCrafter** [comment]
Is there gonna be a 1.19 port of the fix?

**Comment by Boxadactle** [comment]
Sorry, was having problems with forge and my hard drive, should be up by tomorrow

**Comment by TheTrashCrafter** [comment]
Okay, thank you.

**Comment by ImOnTopL** [comment]
Srry school happened its the 1.19 version
