### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by f1xc0d3** [Boxadactle/coordinates-display#20]
**Describe the bug**
Please give a brief and concise description of this bug.

https://pastebin.com/fpLG4zNS

Minecraft Version: 1.20
Loader version: 0.14.21

also Im edit build.gradle: i change id 'fabric-loom' version '0.12-SNAPSHOT' on id 'fabric-loom' version '1.2-SNAPSHOT' although I don't think it matters

**Comment by Boxadactle** [comment]
There isn't a 1.20 port yet, the 1.19.4 version crashes immediately on 1.20
