### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by domo7898** [Boxadactle/coordinates-display#21]
Biom color function ON/OFF
Also, I would like you to add a setting for changing the translation file. If there is already a function, I would like you to tell me how.
1.20 Fabric.

**Comment by Boxadactle** [comment]
Would this toggle only for minimum mode, or for both modes?
Translation files can only be changed in the code, if you'd like to make a translation for this mod, please create a PR on this repository.

**Comment by domo7898** [comment]
> 이것은 최소 모드에서만 토글됩니까, 아니면 두 모드 모두에 대해 토글됩니까? 번역 파일은 코드에서만 변경할 수 있습니다. 이 모드를 번역하려면 이 저장소에서 PR을 생성하세요.


 both modes plz
 Also, there is a KR.lang file in the plug-in folder, but can't you set it to this file?

**Comment by Boxadactle** [comment]
The language files are selected in the Minecraft settings, (Options -> Language)

**Comment by domo7898** [comment]
My setting is Options > Language > Korean.
But mod is not korean

**Comment by Boxadactle** [comment]
There was an error in the Korean json file causing it not to load in-game. Should be fixed soon
