### ISSUE TITLE
Coordinates start position from any corner.

### ISSUE THREAD

**Issue by Sto3IV** [Boxadactle/coordinates-display#22]
I want to display coordinates in top right corner. But in different monitors I need to use different numbers for 	"hudX": 5, "hudY": 3, in config. Can you add option to change start position? 
StartPos: TOP_LEFT, TOP_RIGHT, TOP_CENTER, MIDDLE_LEFT, MIDDLE_RIGHT, MIDDLE_CENTER, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT.

**Comment by Boxadactle** [comment]
Might do this later, it would require a rewrite of the hud position method.
