### ISSUE TITLE
Coordinates on one line

### ISSUE THREAD

**Issue by 4c696e6b** [Boxadactle/coordinates-display#24]
I think a great option would be to put all the coordinates on one line formatted like this:  'X: 100 Y: 60 Z: 1000'

Being able to put the direction on the same line would be nice as well.

**Comment by Boxadactle** [comment]
Like the F3 menu? Not sure how good it would look on high gui scales with the direction all on the same line.

**Comment by Boxadactle** [comment]
![2023-07-13_12 54 20](https://github.com/Boxadactle/coordinates-display/assets/109389081/88c266c9-9ffb-48a2-b947-b1c60aa16d0d)
![image_2023-07-13_130342265](https://github.com/Boxadactle/coordinates-display/assets/109389081/05f6693e-021a-437a-9d19-799fda5d6428)
