### ISSUE TITLE
Bug/Mod conflict discovered - results: world crashes during triggered event

### ISSUE THREAD

**Issue by WilliamBlaze** [Boxadactle/coordinates-display#25]
Although I've already brought the issue up over on Modular Golem's Github, Since the conflict is apparently triggered by something on Coordinates Display's end, I thought I should bring attention to the bug/mod conflict here as well.

the crash log is here though: 

**Describe the bug**
World Crashes

**Reproduce the bug**
1. Have Modular Golems (and its respective libray files) installed alongside Coodinaters Display in the same mod pack
2. Make a Golem Holder (metal golem/humanoid golem/wolf golem holder item) to create a Modular golem.
3. Right clicking on any block with the Golem Holder to summon created Golem into the world. World crashes. Bug appears to only happens ONCE per golem holder type - meaning the bug can only be replicated 3 times per world. (Once for metal golem holder, once for humanoid golem holder, and once for wolf golem holder types.)
4. See error log at https://pastebin.com/AReufFhg

**Expected behavior**
Expected behavior? Being able to use Modular Golems and Coordinates display mods together in the same mod pack without players crashing the entire world.

**Version of Mod (please fill out so I know which version to look for the bug)**
Mod Version: coordinatesdisplay-3.0.0.jar (forge version) 
& modulargolems-2.4.6.jar - (https://legacy.curseforge.com/minecraft/mc-mods/modulargolems/files/4643766)

Mod Loader: Curse Forge Version 47.1.3
Minecraft Version:1.20.1

**Additional context**
That the bug only occurs once per golem holder type, per player, Per world?
It's A Very Oddly Specific Bug, hard to miss, but very consistent in this behavior.

**Comment by Boxadactle** [comment]
Can't seem to recreate this bug with the two mods by themselves, maybe it's caused by another mod. Can you send your entire modlist?

From what it looks like, it's caused when this mod tries to draw the text on the screen, which uses a method written by Mojang, it's entirely possible that one of your other mods changes this behavior in some sort of way.

**Comment by WilliamBlaze** [comment]
No problem Box!

https://pastebin.com/M9NGGr82

I copied and pasted the mod list from the original crash log file into the pastebin link above, it should make reading the lengthy list a tad more Ledgeable compared to the mess of the github Post preview I was working with a moment ago, that was a scrambled mess of yikes!

**Comment by Boxadactle** [comment]
Released a new version that changes how the HUD renders. It now uses Forge's event system rather than mixins, which is what all your other mods seem to be doing. Please tell me if it still crashes.
