### ISSUE TITLE
Nether/Overworld Conversion

### ISSUE THREAD

**Issue by MEJD2004** [Boxadactle/coordinates-display#26]
Is it posible to get conversion between Nether and Overworld Coordinates when in the respective dimensions?

I find that it would help massively with Portal linking if the numbers were neatly displayed in the corner.

**Comment by Boxadactle** [comment]
Will probably add this as a new display mode, it shouldn't take that long to create.

**Comment by Boxadactle** [comment]
![Screenshot 2023-07-31 204701](https://github.com/Boxadactle/coordinates-display/assets/109389081/c872d50e-1432-4320-8cc3-581bbba9d7df)
