### ISSUE TITLE
Keybind to cycle between different display modes

### ISSUE THREAD

**Issue by Oliveoil1** [Boxadactle/coordinates-display#27]
Currently the only way to change display modes is to open up the mod's settings menu and change it through there. 

I think it would be useful to have a keybind to cycle between all of the different modes so, for example, I can bring up the overworld/nether view when I need it without having to pause the game.

**Comment by Boxadactle** [comment]
At the moment, there is a client command to select the display mode, "/coordinates mode (mode)", but I will definitely add this.

**Comment by zgu0802** [comment]
I'm trying to move the coordinates display to the top right corner instead of the left, but the /coordinates movehud command doesn't work and neither does the key bind.
