### ISSUE TITLE
Any way to make coordinates truncate to 0 decimal places, like a block coordinate?

### ISSUE THREAD

**Issue by nomino3390** [Boxadactle/coordinates-display#30]
As it is, if you round to 0 decimal places, two different blocks can have the same coordinates, if you stand on certain sides of them. The behavior in the title would allow precise coordinates for each block, allowing for precise building e.g. vertical elevators, etc.

You can use coords with decimal places and manually truncate, but why would you? That's much less readable. 0 decimal places allows to, for example, see "oh I'm in the X= 200s" at a much quicker glance

**Comment by Boxadactle** [comment]
Gonna change it so it uses block position instead of rounding to 0 decimals, which should fix this issue.

**Comment by nomino3390** [comment]
> Gonna change it so it uses block position instead of rounding to 0 decimals, which should fix this issue.

Awesome, thanks!! Great mod btw.
