### ISSUE TITLE
X direction indicator is shown for Y instead

### ISSUE THREAD

**Issue by NotMurPh** [Boxadactle/coordinates-display#33]
Hey :)

So there is this issue when you go to `display settings` and choose `display mode : minimum` coordinate display shows a + or - indicator next to XYZ coords showing in which direction you are heading for example towards minus X and positive Z
but it has a bug which the one representing the X direction is affected by the Y direction instead!

here is a screen shot showcasing the issue : 
![Untitled (2)](https://github.com/Boxadactle/coordinates-display/assets/66315425/becd6988-d4c0-45e5-be7d-a7eed2686492)

Also thanks for your amazing work :)

**Comment by aczekajski** [comment]
The Z indicator is also wrong.
F3 shows "Towards positive Z" for south directions and "Towards negative Z" for north directions.
However, this is what the mod is showing:
![image](https://github.com/Boxadactle/coordinates-display/assets/3948797/036648e2-db0d-4387-9f3a-7f8d7cf09527)
(red means it's wrong, green when it's ok)

Tested in 1.20.1, Forge, mod version 4.0.0.

**Comment by NotMurPh** [comment]
hey @aczekajski my friend has made a patched fork for this mod which also fixes some other issues like xyz not being accurate and sending location in chat not working, but this fork was only tested in 1.20.1 quilt and may only work for 1.20.x on fabric

here is the link if you want to use it in the mean time: https://github.com/Arian8j2/coordinates-display

**Comment by aczekajski** [comment]
@NotMurPh Thank for pointing me to that. Took me hundred years to figure out why the build fails and another year to actually build but it works :D I added `include("forge")` that was removed from the fork and even the forge version is ok for 1.20.1 ^^

**Comment by Boxadactle** [comment]
Sorry for the inactivity.

I think this is due to how Minecraft stores the yaw. A negative yaw means you are looking up and a positive yaw means you are looking down. The hud determines whether the yaw number is positive or negative and displays the +/-.

Here is a brief fix for 1.20.1 before I eventually backport.
https://github.com/Boxadactle/coordinates-display/actions/runs/7867090243
