### ISSUE TITLE
No toggle hud option in 1.21 fabric

### ISSUE THREAD

**Issue by JoeyFab** [Boxadactle/coordinates-display#40]
idk why but it just isnt there lol

**Comment by Boxadactle** [comment]
The toggle HUD option has been replaced with the "visibility" option (config -> visual settings -> visibility). You can disable the HUD completely by setting the option to "never" or limit the visiblity of the HUD to when you are holding a compass in your hand by setting the option to "holding a compass".

**Comment by Rickrollv2** [comment]
bruh

**Comment by Rickrollv2** [comment]
change this back to a simple keybind smhsmh

**Comment by Gamba04** [comment]
> The toggle HUD option has been replaced with the "visibility" option (config -> visual settings -> visibility). You can disable the HUD completely by setting the option to "never" or limit the visiblity of the HUD to when you are holding a compass in your hand by setting the option to "holding a compass".

@Boxadactle it would be nice to have a new visibility option called "toggle" (or similar) which works with a key bind

**Comment by JoeyFab** [comment]
yeah i agree

**Comment by Boxadactle** [comment]
I've added back the "enabled" option on the main config screen and the "toggle HUD" keybind.
