### ISSUE TITLE
[Request] Show/Hide keybind

### ISSUE THREAD

**Issue by JiFish** [Boxadactle/coordinates-display#42]
I'd like to be able to toggle the visibility of the coordinates with a key. This could either be a new "visibility" option "toggleable", or it could function in all visibility modes.

**Comment by Rickrollv2** [comment]
the fact that this existed before 1.21:

**Comment by JiFish** [comment]
Sorry, I only just got back in to minecraft after a considerable gap. I don't know about any previous versions.

**Comment by Gamba04** [comment]
I would like this too, it would be the perfect replacement for a minimal F3 that can be toggled when needed

**Comment by Gamba04** [comment]
I would like this too, it would be the perfect replacement for a minimal F3 menu that can be toggled when needed
