### ISSUE TITLE
"Round when copying" is inverted

### ISSUE THREAD

**Issue by Gamba04** [Boxadactle/coordinates-display#43]
It rounds if set to **No** and doesn't if set to **Yes**

https://github.com/Boxadactle/coordinates-display/assets/63524957/aa0e1165-62d4-4430-aeda-65f24c65c3ba

**Comment by Boxadactle** [comment]
I've fixed the language on the button.
![Screenshot_20240706_224232](https://github.com/Boxadactle/coordinates-display/assets/109389081/a41d41dc-4e63-4452-abaa-4f119c0bf45e)
