### ISSUE TITLE
11.1.0 Crashes

### ISSUE THREAD

**Issue by Gamba04** [Boxadactle/coordinates-display#44]
![image](https://github.com/Boxadactle/coordinates-display/assets/63524957/bb61f1a4-7019-4dee-83e3-9171a3b6c2f2)

Here's the [crash report](https://github.com/user-attachments/files/16121510/crash-2024-07-07_19.20.52-client.txt) in case you need it.

**Comment by Boxadactle** [comment]
I've removed the "never" visibility option, but I accidentally forgot to add a patch for the config. I will release an update soon, but right now you can fix the error by opening the config file (.minecraft/config/coordinates-display.json) and changing "visibilityFilter" to "always"

**Comment by Gamba04** [comment]
Hey! I found another crash that occurs when cycling forward between display modes with the hotkey after the "Chunk" mode.

![image](https://github.com/Boxadactle/coordinates-display/assets/63524957/f92861d4-a197-46c4-9c9b-7eeb0145b9c5)

I figured I'd stick it in here because it's related so you can find both crashes related to this version in the same place.

Here's the [crash report](https://github.com/user-attachments/files/16133893/crash-2024-07-08_14.34.27-client.txt).
