### ISSUE TITLE
[1.20.6] Crash on loading w/ fresh installation

### ISSUE THREAD

**Issue by Lucipo** [Boxadactle/coordinates-display#51]
## Clear and Consise description of the issue

**What happened**?
Game crashes when trying to load

**What did you expect to happen?**
Fully launch into game

**Steps to reproduce the issue:**
Install mods on fabric 1.20.6 by themselves alongside fab api, launch, crash
 * FYI this is a fresh installation and crashes. Got same crash on my other 1.20.6 pack with 200 other mods.
## Mod Information
**Minecraft version:** 1.20.6
**Mod version:** 10.0.0
**Other relevant mods:** boxlib 13.2.1

**Relevant logs (if applicable):**
Pastebin link or attachment
[crash-2024-07-22_04.53.26-client.txt](https://github.com/user-attachments/files/16331489/crash-2024-07-22_04.53.26-client.txt)

**Comment by Vahpurr** [comment]
Same/similar issue:
Downloaded and installed today's update (7/22/24) for CoordinatesDIsplay, as well as the most recent BoxLib (7/20/24). 

![Screenshot 2024-07-22 120321](https://github.com/user-attachments/assets/7fee9287-a336-4d5e-8c74-7459e8ca32fe)
![Screenshot 2024-07-22 120153](https://github.com/user-attachments/assets/ba1cf293-cbae-47a8-bb3d-514c5035a9da)


Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'CoordinatesDisplay' (coordinatesdisplay) 7.1.0 with any version that is compatible with:
		 - minecraft 1.21
		 - boxlib 14.2.1
More details:
	 - Mod 'CoordinatesDisplay' (coordinatesdisplay) 7.1.0 requires version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	 - Mod 'CoordinatesDisplay' (coordinatesdisplay) 7.1.0 requires any 8.x version of mod 'BoxLib' (boxlib), but only the wrong version is present: 14.2.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
_____________________________________________________________
exit Code: 1

**Comment by Boxadactle** [comment]
I'm currently in the process of backporting this mod, and I've recently removed a feature from Boxlib that this mod is trying to use. Please try to use an older version of Boxlib until I can update the 1.20.6 version. 
https://modrinth.com/mod/boxlib/version/13.0.2

**Comment by Vahpurr** [comment]
> I'm currently in the process of backporting this mod, and I've recently removed a feature from Boxlib that this mod is trying to use. Please try to use an older version of Boxlib until I can update the 1.20.6 version. https://modrinth.com/mod/boxlib/version/13.0.2

__________________________________________
Apologies for the basic question; using the older BoxLib gives the same crash error. Which older CoordDisplay should I try with this? 
_________________________________________________

![Screenshot 2024-07-22 121536](https://github.com/user-attachments/assets/c0174371-3060-4f03-8a22-86467898938f)

**Comment by Boxadactle** [comment]
The Coordinates display version that you're trying to use is the most recent but it's for minecraft 1.19.3, here is an older version for 1.20.6: https://modrinth.com/mod/coordinates-display/version/10.0.0-fabric

**Comment by Boxadactle** [comment]
This issue has been fixed in the latest update.
