### ISSUE TITLE
Minecraft cooridinate

### ISSUE THREAD

**Issue by spookiecheez** [Boxadactle/coordinates-display#56]
## Clear and concise description of your problem

**What are you trying to achieve?* Installed the Coordinate display mod for Minecraft . Went through the step by step installation instructions . My problem is that there's no instructions on how to get it to work after the install is complete.  I'm running minecraft java using fabric.

Can you please send instructions on how to get it to work?
**What is happening instead?**

## Relevant details about your setup
**Minecraft version:**
**Mod version:**

**Comment by Boxadactle** [comment]
If the game is not launching - Make sure BoxLib and Fabric API are installed.
If it is not displaying - It might be disabled, press H in-game and if that doesn't work enter config gui from mod menu -> enabled -> yes
