### ISSUE TITLE
Game crash while using coordinates-display

### ISSUE THREAD

**Issue by HugoDryBread** [Boxadactle/coordinates-display#58]
## Clear and Consise description of the issue

**What happened**?

game crashed add the end of the world initiliziation

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_340 net.minecraft.class_310.method_53526()'

**What did you expect to happen?**

Game start

**Steps to reproduce the issue:**

Put the mod in mods folder (I tried to remove it and averithing works fine)

## Mod Information
**Minecraft version:** 1.20.1
**Mod version:** 10.1.1
**Other relevant mods:** 

 - Boxlib-fabric-11.3.2
 - collective-1.20.1-7.84
 - continuity-3.0.0-beta.5+1.20.1
 - entityculling-fabric-1.7.0-mc1.20.1
 - fabric-api-0.92.2+1.20.1
 - fullbrightnesstoggle-1.20.1-4.2
 - indium-1.0.34+mc1.20.1
 - iris-1.7.2+mc1.20.1
 - simple-hud-enhanced+1.20-1.20.1-4.7.2
 - sodium-fabric-0.5.11+mc1.20.1
 - CoordinatesDisplay-fabric-10.1.1

**Relevant logs (if applicable):**
[crash-2024-09-23_22.40.16-client.txt](https://github.com/user-attachments/files/17104065/crash-2024-09-23_22.40.16-client.txt)

**Comment by Poopooracoocoo** [comment]
It appears that versions 10.1.0 ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/coordinates-display/files/5555480), [Modrinth](https://modrinth.com/mod/coordinates-display/version/10.1.0-fabric)) and 10.1.1 ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/coordinates-display/files/5639495), [Modrinth](https://modrinth.com/mod/coordinates-display/version/10.1.1-fabric)) were mistakenly marked as being for 1.20.1 as well as 1.20.2 on CurseForge and Modrinth. They seem to only be for 1.20.2. 

7.0.0 ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/coordinates-display/files/5127075), [Modrinth](https://modrinth.com/mod/coordinates-display/version/7.0.0-fabric)) seems to be the actual last 1.20.1 release.

**Comment by Boxadactle** [comment]
This issue has been fixed. Please update to the newest version 9.2.0 for 1.20.1.
