### ISSUE TITLE
Intallation

### ISSUE THREAD

**Issue by Ecne1is** [Boxadactle/coordinates-display#60]
Hello! I'm so glad to have an opportunity to have the library and mods but i'd a problem with an installation. There's no instructions at all how come should i install it. Please leave me an instruction how to install your boxlib and coordinates display mod together for 1.20.4 version of minecraft. Thank you in advance!

**Comment by Ecne1is** [comment]
I mean I've been confused. First of all i followed the main instruction like just download BoxLib and CoordinateDisplay mods (the FabricApi and modmenu have been installed) but then i tried to launch the game and it crashes. So i've wonder if i miss something and then i found instruction where i found some setups at https://modrinth.com/mod/boxlib. I couldn't unserstand but anyway i tried purposefully. Then i found some "building"s at https://www.curseforge.com/minecraft/mc-mods/coordinates-display in the end of the page like download .zip unzip it then open gradlew build. So as a consequience nothing has hepled me. Please help me

**Comment by Ecne1is** [comment]
I solved the problem. Well i just deleted BoxLib and latest available CoordinateDisplay and downloaded only CoordinateDisplay mod but 6.0.0 (which is an old or the oldest one o guess) and just moved it to mods folder. https://cdn.modrinth.com/data/3mW8PdUo/versions/7B2Qo6v9/CoordinatesDisplay-6.0.0.jar

**Comment by Ecne1is** [comment]
I solved the problem. Well i just deleted BoxLib and latest available CoordinateDisplay and downloaded only CoordinateDisplay mod but 6.0.0 (which is an old or the oldest one for 1.20.4 in particular i guess) and just moved it to mods folder. https://cdn.modrinth.com/data/3mW8PdUo/versions/7B2Qo6v9/CoordinatesDisplay-6.0.0.jar

**Comment by Boxadactle** [comment]
I have recompiled Boxlib for 1.20.4 with the correct java version. Please update it and coordinates display to the latest versions on Modrinth.

**Comment by Ecne1is** [comment]
Everything i have is only the latest versions. But i would like to try if you leave a link to download said version of BoxLib :D
