### ISSUE TITLE
Java 1.21.3 Coordinates Display crashes game at launch

### ISSUE THREAD

**Issue by Vahpurr** [Boxadactle/coordinates-display#61]
Coordinates Display was working yesterday and all through today 10/23/2024; appx 9:00 CST I toggled the display by accident; trying to toggle back on triggered "save world" crash, and now will not launch.

Removing Coordintates Display and Boxlib allows the game to load properly; fabric launcher 1.21.3

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_332.method_25290(net.minecraft.class_2960, int, int, float, float, int, int, int, int)'

[crash-2024-10-23_21.20.57-client.txt](https://github.com/user-attachments/files/17500279/crash-2024-10-23_21.20.57-client.txt)

**Comment by Vahpurr** [comment]
10/24 
Confirmed crash before terrain loading on both multiplayer server and singleplayer world, when Coordinates Display is present in the mods folder. 
Game loads as expected with boxlib present in mods folder.

**Comment by Boxadactle** [comment]
This mod has not yet been updated to 1.21.3 and there might be a lot of crashes. For now please avoid using the spawnpoint render mode and all client commands. To be safe, do not configure the mod either. To fix crashing delete config file (.minecraft/config/coordinatesdisplay.json) and restart the game.

**Comment by Vahpurr** [comment]
Thank you so much for the workaround. I am happy to be able to have it load at all.
