### ISSUE TITLE
Incompatibility with Boxlib Version (1.20.1)

### ISSUE THREAD

**Issue by YJjc0207** [Boxadactle/coordinates-display#64]
## Clear and Consise description of the issue

**What happened**?
I download the latest version of both boxlib and coordinates display for minecraft 1.20.1 but they aren't compatible with each other

**What did you expect to happen?**

**Steps to reproduce the issue:**

## Mod Information
**Minecraft version: 1.20.1 **
**Mod version: Coordinates Display 9.2.0, Boxlib 11.3.2**
**Other relevant mods:**

**Relevant logs (if applicable):**
Pastebin link or attachment

## Screenshots or videos: (Optional)
<img width="789" alt="Captura de pantalla 2024-12-19 a la(s) 4 51 53 p m" src="https://github.com/user-attachments/assets/de62e233-392f-425a-ab33-563b734289b2" />
<img width="1019" alt="Captura de pantalla 2024-12-19 a la(s) 4 50 34 p m" src="https://github.com/user-attachments/assets/9ce498c0-a9a4-45b6-83a8-31b9aa31bc65" />

**Comment by Boxadactle** [comment]
9.2.0 is only for 1.20, and was accidentally mislabeled. Please use any 10.x version for 1.20.1
