### ISSUE TITLE
game crashes when i press play on minecraft installer

### ISSUE THREAD

**Issue by ThePotato6801** [Boxadactle/coordinates-display#7]
**Description of crash**
What were you when the game crashed?

**To Reproduce**
Steps to reproduce the crash:
4. Game crashes

**Version (please complete the following information):**
 - OS: 
 - Mod Loader: 
 - Mod Version: 
 - Minecraft Version: 

**Error Log**
```
Please paste your error log here
```

**Comment by Boxadactle** [comment]
Sorry. but you haven't provided enough details for me to look for the error.
