### ISSUE TITLE
Facing Coords

### ISSUE THREAD

**Issue by Hybjis** [Boxadactle/coordinates-display#9]
I would like to be able to see facing coords (coordinates that show which direction you're facing, ranging from -180 to 180). In the screenshots of the mod it seems to be there next to the direction (east, west). But I can't find any setting to enable it. This would be very useful for parkour as you need to line yourself up in a certain direction.

**Comment by Boxadactle** [comment]
Yeah, the preview of the mod is really outdated and I haven't been able to update it yet. That feature was deprecated a while ago, but I plan on adding it back on the next update.

**Comment by Boxadactle** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/109389081/227747665-208f614f-443f-42b4-8c0d-3e9739ef4df6.png)
